# Docker Compose override for development testing
# This file extends docker-compose.test.yml for development use

version: '3.8'

services:
  # Development test runner with live code mounting
  test-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile_test
    container_name: mcp-neo4j-test-dev
    environment:
      - NEO4J_URI=neo4j://neo4j-test:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=testpassword
      - NEO4J_DATABASE=neo4j
    depends_on:
      neo4j-test:
        condition: service_healthy
    networks:
      - test-network
    volumes:
      # Live mounting for development
      - ../src:/app/src
      - ../tests:/app/tests
      - ../test-results:/app/test-results
    # Interactive shell for development
    stdin_open: true
    tty: true
    command: ["/wait-for-neo4j.sh", "/bin/bash"]

  # Watch mode for continuous testing during development
  test-watch:
    build:
      context: ..
      dockerfile: docker/Dockerfile_test
    container_name: mcp-neo4j-test-watch
    environment:
      - NEO4J_URI=neo4j://neo4j-test:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=testpassword
      - NEO4J_DATABASE=neo4j
    depends_on:
      neo4j-test:
        condition: service_healthy
    networks:
      - test-network
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
      - ../test-results:/app/test-results
    # Install and use pytest-watch for continuous testing
    command: [
      "/wait-for-neo4j.sh",
      "sh", "-c",
      "uv add pytest-watch && ptw tests/ -- -v"
    ]
