version: '3.8'

services:
  librechat:
    image: ghcr.io/danny-avila/librechat:latest
    container_name: librechat
    ports:
      - "3080:3080"
    depends_on:
      - mongodb
      - neo4j
      - mcp-neo4j-memory
    volumes:
      - ../examples/librechat-sse.yaml:/app/librechat.yaml:ro
      - ./logs:/app/api/logs
      - ./uploads:/app/client/public/uploads
    environment:
      - NODE_ENV=production
      - CONFIG_PATH=/app/librechat.yaml
    networks:
      - librechat-network
    restart: unless-stopped

  mcp-neo4j-memory:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: sse
    environment:
      - MCP_MODE=sse
      - NEO4J_URL=neo4j://neo4j:7687
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    networks:
      - librechat-network

  neo4j:
    image: neo4j:latest
    container_name: neo4j-memory-db
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - librechat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "${NEO4J_PASSWORD}", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  mongodb:
    image: mongo:6-jammy
    container_name: librechat-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - librechat-network
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  mongodb_data:

networks:
  librechat-network:
    driver: bridge
