name: MCP Neo4j Data Modeling Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'servers/mcp-neo4j-data-modeling/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'servers/mcp-neo4j-data-modeling/**'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install UV
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        cd servers/mcp-neo4j-data-modeling
        uv venv
        uv pip install -e ".[dev]"

    - name: Check format and linting
      run: |
        cd servers/mcp-neo4j-data-modeling
        make format
    
    - name: Run tests
      run: |
        cd servers/mcp-neo4j-data-modeling
        make test